spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://configuration-server-one:8888,optional:configserver:http://configuration-server-two:8888
  cloud:
    config:
      label: 09-k8s
      fail-fast: true

