logging:
  level:
    org.javamoney.moneta: OFF
eureka:
  client:
    should-enforce-registration-at-init: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
# resource server
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/training
# oauth2 login/client
      client:
        registration:
          keycloak:
            client-id: cloud
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8100/realms/training