logging:
  level:
    org.javamoney.moneta: OFF
eureka:
  client:
    should-enforce-registration-at-init: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    instance:
      hostname: localhost
# resource server
spring:
  cloud:
    function:
      definition: blockedTokenConsumer
    stream:
      bindings:
        blockedTokenConsumer-in-0:
          destination: blocked-tokens
          group: ${random.uuid} #shop
          properties:
            spring.json.trusted.packages: pl.training.events.BlockedToken
        blocked-tokens-out-0:
          destination: blocked-tokens
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/training
 # oauth2 login/client
#      client:
#        registration:
#          keycloak:
#            client-id: training-client
#            scope:
#              - openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8100/realms/training