spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: shop-route
            predicates:
              - Path=/api/shop/**
            uri: lb://SHOP-SERVICE
            filters:
            - RewritePath=/api/shop(?<segment>.*), $\{segment}
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
