#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: shop-route
#          predicates:
#            - Path=/api/shop/**
#          uri: lb://PAYMENTS-SERVICE
#          filters:
#            - RewritePath=/api/shop(?<segment>.*), $\{segment}
#            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080/api/shop
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
