spring:
  cloud:
    gateway:
      routes:
        - id: shop-route
          predicates:
            - Path=/api/shop/**
          uri: lb://SHOP-SERVICE
          filters:
            - RewritePath=/api/shop(?<segment>.*), $\{segment}
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080/api/shop
            - RequestLogger=info,loggingFilter
            - RequestTime=8:00,17:00
