spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
  messages:
    basename: exceptions
  cloud:
    openfeign:
      client:
        config:
          timeProvider:
            logger-level: basic
    stream:
      #      kafka:
      #        binder:
      #          brokers: localhost:9092
      bindings:
        payments-out-0:
          destination: payment-events
api:
  time: https://timeapi.io/api/time/current/zone?timeZone=Europe%2FWarsaw

