spring:
  datasource:
    url: jdbc:postgresql://postgres-server:5432/training
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
  messages:
    basename: exceptions
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka-server:9092
      bindings:
        payments-out-0:
          destination: payment-events
api:
  time: http://worldtimeapi.org/api/timezone/Europe/Warsaw
