discount: 10
api:
  payments: http://payments-service:8080/payments
spring:
  cloud:
    function:
      definition: paymentEventsConsumer
    stream:
      kafka:
        binder:
          brokers: kafka-server:9092
      bindings:
        paymentEventsConsumer-in-0:
          destination: payment-events
          group: shop
