#logging:
#  level:
#    org.springframework.web.client.RestTemplate: DEBUG
spring:
  cloud:
    openfeign:
      client:
        config:
          PAYMENTS-SERVICE: #default:
            logger-level: basic
