logging:
  level:
    #org.springframework.web.client.RestTemplate: DEBUG
    pl.training: DEBUG
spring:
  cloud:
    openfeign:
      client:
        config:
          PAYMENTS-SERVICE: #default:
            logger-level: basic
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/shop-db-development.db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
