logging:
  level:
    pl.training: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG;
spring:
  cloud:
    openfeign:
      client:
        config:
          PAYMENTS_SERVICE: #default:
            logger-level: basic