spring:
  application:
    name: shop-service
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://localhost:8889
  cloud:
    config:
      label: 07-Tracing-and-monitoring
encrypt:
  key: JYMMETRICJEYP
management:
  endpoints:
    web:
      exposure:
        include: health,refresh