POST http://localhost:10000/payments
Accept: application/json
Content-Type: application/json
Authorization: bearer {{token}}

{
  "value": "200 PLN"
}

###

GET http://localhost:10000/payments/1260044c-3814-4cba-aefc-ccbad56ecd93
Accept: application/json
Content-Type: application/json

###

GET http://localhost:10000/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json

# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties

###

GET http://localhost:8888/01-Configuration-server/application-default.yml

###

GET http://localhost:8888/01-Configuration-server/application-development.json

###

GET http://localhost:8888/03-Gateway-server/payments-service-development.properties

###

GET http://localhost:8888/application/default/01-Configuration-server/data.xml

###

POST http://localhost:8080/api/shop/payments
Accept: application/json
Content-Type: application/json

{
  "value": "200 PLN"
}

###

POST http://localhost:8888/encrypt
Content-Type: text/plain

Hello

###

POST http://localhost:8888/decrypt
Content-Type: text/plain

ae0d9b87c6c7aae3daf5adcbfc48372234dc3d073acee2391334bced7b94de05

###

GET http://localhost:8888/03-Gateway-server/shop-service.properties

###

POST http://localhost:20000/orders
Accept: application/json
Content-Type: application/json
Authorization: bearer {{token}}

{
  "entries": [
    {
      "productId": 1,
      "quantity": 10,
      "price": 1000
    }
  ]
}


###

POST http://localhost:20000/actuator/refresh

###

POST http://localhost:8888/monitor
Content-Type: application/x-www-form-urlencoded

path=shop-service

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=password&username=jan&password=123

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=refresh_token&refresh_token={{refreshToken}}

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}