POST http://localhost:10000/payments
Accept: application/json
Content-Type: application/json

{
  "value": "200 PLN"
}

###

GET http://localhost:10000/payments/1260044c-3814-4cba-aefc-ccbad56ecd93
Accept: application/json
Content-Type: application/json

###

GET http://localhost:10000/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json
