services:
  postgres-server:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=training
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  zookeeper-server:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-server:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
  keycloak:
    image: quay.io/keycloak/keycloak
    command:
      - start-dev
    ports:
      - "8100:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "postgres-server"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      DB_DATABASE: "training"
