services:
  zookeeper-server:
    image: wurstmeister/zookeeper
    restart: on-failure
  kafka-server:
    image: wurstmeister/kafka
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-server
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
  configuration-server-one:
    image: configuration-server
    restart: on-failure
    environment:
      GIT_URI: https://github.com/landrzejewski/spring-cloud
      SEARCH_PATHS: configuration-files
      KAFKA_BROKERS: kafka-server:9092
      ENCRYPT_KEY: JYMMETRICJEYP
    volumes:
      - ./volumes/configuration-server-one:/data
  configuration-server-two:
    image: configuration-server
    restart: on-failure
    environment:
      GIT_URI: https://github.com/landrzejewski/spring-cloud
      SEARCH_PATHS: configuration-files
      KAFKA_BROKERS: kafka-server:9092
      ENCRYPT_KEY: JYMMETRICJEYP
    volumes:
      - ./volumes/configuration-server-two:/data
#  discovery-server:
#    image: discovery-server
#    restart: on-failure
#    ports:
#      - "8761:8761"
#    deploy:
#      replicas: 2
  gateway-server:
    image: gateway-server
    restart: on-failure
    ports:
      - "8080:8080"
  postgres-server:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=training
    volumes:
      - ./volumes/postgres-server:/var/lib/postgresql/data
  payments-service:
    image: payments-service
    restart: on-failure
    deploy:
      replicas: 2
  shop-service:
    image: shop-service
    restart: on-failure
    deploy:
      replicas: 2
