server:
  port: 8888
spring:
#  profiles:
#    active: jdbc,git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landrzejewski/spring-cloud
          skip-ssl-validation: true
          try-master-branch: false
          search-paths: configuration-files
          order: 0
        encrypt:
          enabled: false
  #        jdbc:
#          order: 1
#          sql: "SELECT properties.prop_key, properties.prop_value from properties where application=? and profile=? and label=?"
  datasource:
    url: jdbc:h2:file:./data/config.db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
encrypt:
  key: SYMWWOQWCFEY
