server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landrzejewski/spring-cloud
          skip-ssl-validation: true
          search-paths: configuration-files
