server:
  port: 8888
spring:
#  profiles:
#    active: git, jdbc
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landrzejewski/spring-cloud
          search-paths: configuration-files
          # skip-ssl-validation: true
          order: 1
#        jdbc:
#          sql: "SELECT prop_key, prop_value from properties where application=? and profile=? and label=?"
#          order: 0
        encrypt:
          enabled: false
#  datasource:
#    url: jdbc:h2:file:./data/configuration-development.db;DB_CLOSE_ON_EXIT=FALSE
#    username: admin
#    password: admin
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      path: /h2
#      enabled: true
encrypt:
  key: JYMMETRICJEYP