spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://configuration-server-one:8888,optional:configserver:http://configuration-server-two:8889
  cloud:
    config:
      label: 10-k8s
      #fail-fast: true
