spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://localhost:8889
  cloud:
    config:
      label: 10-k8s
      #fail-fast: true
