apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: training
  name: kafka-deployment
  annotations:
    kubernetes.io/change-cause: "Initial release"
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: kafka-server
  template:
    metadata:
      labels:
        app-name: kafka-server
    spec:
      containers:
        - name: kafka-server
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
