apiVersion: v1
kind: ConfigMap
metadata:
  namespace: training
  name: payments-config-map
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/training"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "admin"
