apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: training
spec:
  hostPath:
    path: /tmp/postgres-volume
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
